const DashboardActionTypes = {
  ADD_FILE: 'DASHBOARD/ADD_FILE',
  REMOVE_FILE: 'DASHBOARD/REMOVE_FILE',
  GO_BACK: 'DASHBOARD/GO_BACK',
  GO_FORWARD: 'DASHBOARD/GO_FORWARD',
  NAVIGATE_ABSOLUTE: 'DASHBOARD/NAVIGATE_ABSOLUTE',
};

export default DashboardActionTypes;
